---
variables:
  DOCKER_HUB_IMAGE: "${DOCKER_HUB_USERNAME}/${CI_PROJECT_NAME}"
  # renovate: datasource=docker depName=python
  PYTHON_VERSION: "3.12.8-bullseye"
  # renovate: release=bullseye depName=trac
  TRAC_VERSION: "1.4.3"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

stages:
- test
- build
- docs

kaniko-check:
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  rules:
  - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  script:
  - /kaniko/executor --context="${CI_PROJECT_DIR}" --dockerfile="${CI_PROJECT_DIR}/Dockerfile" --no-push
  - echo "Would publish new image ${CI_REGISTRY_IMAGE}:${TRAC_VERSION}.${CI_PIPELINE_IID}_python${PYTHON_VERSION}"
  - echo "Would publish new image ${DOCKER_HUB_IMAGE}:${TRAC_VERSION}.${CI_PIPELINE_IID}_python${PYTHON_VERSION}"
  stage: test
  tags:
  - kubernetes

kaniko:
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
  - mkdir --parents /kaniko/.docker
  - |
    echo "{
      \"auths\": {
        \"${CI_REGISTRY}\": {
          \"username\": \"${CI_REGISTRY_USER}\",
          \"password\": \"${CI_REGISTRY_PASSWORD}\"
        },
        \"${DOCKER_HUB_URL}\": {
          \"username\": \"${DOCKER_HUB_USERNAME}\",
          \"password\": \"${DOCKER_HUB_PASSWORD}\"
        }
      }
    }" > /kaniko/.docker/config.json
  - /kaniko/executor --context="${CI_PROJECT_DIR}" --destination="${CI_REGISTRY_IMAGE}:${TRAC_VERSION}.${CI_PIPELINE_IID}_python${PYTHON_VERSION}" --destination="${DOCKER_HUB_IMAGE}:${TRAC_VERSION}.${CI_PIPELINE_IID}_python${PYTHON_VERSION}" --dockerfile="${CI_PROJECT_DIR}/Dockerfile"
  - echo "Successfully published new image ${CI_REGISTRY_IMAGE}:${TRAC_VERSION}.${CI_PIPELINE_IID}_python${PYTHON_VERSION}"
  - echo "Successfully published new image ${DOCKER_HUB_IMAGE}:${TRAC_VERSION}.${CI_PIPELINE_IID}_python${PYTHON_VERSION}"
  stage: build
  tags:
  - kubernetes

docker-hub:
  image: alpine/curl:8.11.1
  rules:
  - changes:
    - README.md
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
  - apk add jq
  - |
    DOCKER_HUB_TOKEN="$(curl --request POST --header "content-type: application/json" "${DOCKER_HUB_API_URL}users/login" --data-raw "{\"username\": \"${DOCKER_HUB_USERNAME}\", \"password\": \"${DOCKER_HUB_PASSWORD}\"}" | jq -r .token)"
    README_CONTENT="$(cat README.md)"
    echo "${README_CONTENT}"
    README_CONTENT="${README_CONTENT//$'\\'/\\\\}"
    README_CONTENT="${README_CONTENT//$'\n'/\\n}"
    echo "${README_CONTENT}"
    curl --request PATCH --header "Authorization: Bearer ${DOCKER_HUB_TOKEN}" --header "content-type: application/json" "${DOCKER_HUB_API_URL}repositories/${DOCKER_HUB_USERNAME}/${CI_PROJECT_NAME}/" --data-raw "{\"full_description\": \"${README_CONTENT}\"}"
  stage: docs
  tags:
  - kubernetes
